language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
sudo: false
dist: xenial
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.9
      env: GROUP=docs
      addons:
        apt:
          packages:
            - pandoc
      script:
        - python -m pytest_check_links
        - cd docs
        - make html
        - make linkcheck
cache:
  pip: true
  directories:
    - ~/.npm  # NPM cache
before_install:
  - pip install -U pip setuptools
  - nvm install 8
install:
  - pip install --upgrade -e ".[test, examples, docs]"
script:
  - py.test -l --nbval-lax --current-env examples
